"""Doom thing type catalog — Doom 1, Ultimate Doom, and Doom 2.

Covers all standard Doom thing types plus the MBF Helper Dog (#888).
"""

from .base import GameModule, ThingCategory

_TABLE: list[tuple[int, str, ThingCategory]] = [
    # ---- Player spawns ---------------------------------------------------------
    (1, "Player 1 Start", ThingCategory.PLAYER),
    (2, "Player 2 Start", ThingCategory.PLAYER),
    (3, "Player 3 Start", ThingCategory.PLAYER),
    (4, "Player 4 Start", ThingCategory.PLAYER),
    (11, "Deathmatch Start", ThingCategory.DECORATION),
    (14, "Teleport Landing", ThingCategory.DECORATION),
    # ---- Monsters (Doom 1 + 2) -------------------------------------------------
    (3004, "Zombieman", ThingCategory.MONSTER),
    (9, "Shotgun Guy", ThingCategory.MONSTER),
    (65, "Chaingunner", ThingCategory.MONSTER),
    (3001, "Imp", ThingCategory.MONSTER),
    (3002, "Demon", ThingCategory.MONSTER),
    (58, "Spectre", ThingCategory.MONSTER),
    (3003, "Baron of Hell", ThingCategory.MONSTER),
    (3005, "Cacodemon", ThingCategory.MONSTER),
    (3006, "Lost Soul", ThingCategory.MONSTER),
    (7, "Spider Mastermind", ThingCategory.MONSTER),
    (16, "Cyberdemon", ThingCategory.MONSTER),
    (64, "Arch-Vile", ThingCategory.MONSTER),
    (66, "Revenant", ThingCategory.MONSTER),
    (67, "Mancubus", ThingCategory.MONSTER),
    (68, "Arachnotron", ThingCategory.MONSTER),
    (69, "Hell Knight", ThingCategory.MONSTER),
    (71, "Pain Elemental", ThingCategory.MONSTER),
    (72, "Commander Keen", ThingCategory.MONSTER),
    (84, "Wolfenstein SS", ThingCategory.MONSTER),
    (88, "Boss Brain", ThingCategory.MONSTER),
    (888, "MBF Helper Dog", ThingCategory.MONSTER),
    # ---- Keys ------------------------------------------------------------------
    (5, "Blue Keycard", ThingCategory.KEY),
    (6, "Yellow Keycard", ThingCategory.KEY),
    (13, "Red Keycard", ThingCategory.KEY),
    (38, "Red Skull Key", ThingCategory.KEY),
    (39, "Yellow Skull Key", ThingCategory.KEY),
    (40, "Blue Skull Key", ThingCategory.KEY),
    # ---- Weapons ---------------------------------------------------------------
    (82, "Super Shotgun", ThingCategory.WEAPON),
    (2001, "Shotgun", ThingCategory.WEAPON),
    (2002, "Chaingun", ThingCategory.WEAPON),
    (2003, "Rocket Launcher", ThingCategory.WEAPON),
    (2004, "Plasma Rifle", ThingCategory.WEAPON),
    (2005, "Chainsaw", ThingCategory.WEAPON),
    (2006, "BFG 9000", ThingCategory.WEAPON),
    # ---- Ammo ------------------------------------------------------------------
    (17, "Energy Cell", ThingCategory.AMMO),
    (8, "Backpack", ThingCategory.AMMO),
    (2007, "Ammo Clip", ThingCategory.AMMO),
    (2008, "Shotgun Shells", ThingCategory.AMMO),
    (2010, "Rocket", ThingCategory.AMMO),
    (2046, "Box of Rockets", ThingCategory.AMMO),
    (2047, "Energy Cell Pack", ThingCategory.AMMO),
    (2048, "Box of Ammo", ThingCategory.AMMO),
    (2049, "Box of Shells", ThingCategory.AMMO),
    # ---- Health ----------------------------------------------------------------
    (2011, "Stimpack", ThingCategory.HEALTH),
    (2012, "Medikit", ThingCategory.HEALTH),
    (2013, "Soulsphere", ThingCategory.HEALTH),
    (2014, "Health Bonus", ThingCategory.HEALTH),
    # ---- Armor -----------------------------------------------------------------
    (2015, "Armor Bonus", ThingCategory.ARMOR),
    (2018, "Green Armor", ThingCategory.ARMOR),
    (2019, "Blue Armor", ThingCategory.ARMOR),
    # ---- Powerups --------------------------------------------------------------
    (83, "Megasphere", ThingCategory.POWERUP),
    (2022, "Invulnerability", ThingCategory.POWERUP),
    (2023, "Berserk Pack", ThingCategory.POWERUP),
    (2024, "Partial Invisibility", ThingCategory.POWERUP),
    (2025, "Radiation Suit", ThingCategory.POWERUP),
    (2026, "Computer Map", ThingCategory.POWERUP),
    (2045, "Light Amp Goggles", ThingCategory.POWERUP),
    # ---- Decorations (subset) --------------------------------------------------
    (10, "Bloody Mess", ThingCategory.DECORATION),
    (12, "Pool of Blood", ThingCategory.DECORATION),
    (15, "Dead Player", ThingCategory.DECORATION),
    (18, "Dead Zombieman", ThingCategory.DECORATION),
    (19, "Dead Shotgun Guy", ThingCategory.DECORATION),
    (20, "Dead Imp", ThingCategory.DECORATION),
    (21, "Dead Demon", ThingCategory.DECORATION),
    (22, "Dead Cacodemon", ThingCategory.DECORATION),
    (23, "Dead Lost Soul", ThingCategory.DECORATION),
    (24, "Pool of Blood", ThingCategory.DECORATION),
    (25, "Impaled Human", ThingCategory.DECORATION),
    (26, "Twitching Impaled", ThingCategory.DECORATION),
    (27, "Skull on a Pole", ThingCategory.DECORATION),
    (28, "Five Skulls", ThingCategory.DECORATION),
    (29, "Pile of Skulls", ThingCategory.DECORATION),
    (30, "Tall Green Column", ThingCategory.DECORATION),
    (31, "Short Green Column", ThingCategory.DECORATION),
    (32, "Tall Red Column", ThingCategory.DECORATION),
    (33, "Short Red Column", ThingCategory.DECORATION),
    (34, "Candle", ThingCategory.DECORATION),
    (35, "Candelabra", ThingCategory.DECORATION),
    (36, "Tall Skull Column", ThingCategory.DECORATION),
    (37, "Short Skull Column", ThingCategory.DECORATION),
    (41, "Evil Eye", ThingCategory.DECORATION),
    (42, "Floating Skull", ThingCategory.DECORATION),
    (43, "Burnt Tree", ThingCategory.DECORATION),
    (44, "Tall Blue Firestick", ThingCategory.DECORATION),
    (45, "Tall Green Firestick", ThingCategory.DECORATION),
    (46, "Tall Red Firestick", ThingCategory.DECORATION),
    (47, "Stalagtite", ThingCategory.DECORATION),
    (48, "Techno Column", ThingCategory.DECORATION),
    (49, "Hanging Body", ThingCategory.DECORATION),
    (50, "Hanging Torso", ThingCategory.DECORATION),
    (51, "One-Legged Body", ThingCategory.DECORATION),
    (52, "Hanging Pair Legs", ThingCategory.DECORATION),
    (53, "Hanging Leg", ThingCategory.DECORATION),
    (54, "Large Brown Tree", ThingCategory.DECORATION),
    (55, "Short Blue Firestick", ThingCategory.DECORATION),
    (56, "Short Green Firestick", ThingCategory.DECORATION),
    (57, "Short Red Firestick", ThingCategory.DECORATION),
    (59, "Hanging Body Twitching", ThingCategory.DECORATION),
    (60, "Hanging Body Arms Out", ThingCategory.DECORATION),
    (61, "Hanging Torso Looking Down", ThingCategory.DECORATION),
    (62, "Hanging Torso Open Brain", ThingCategory.DECORATION),
    (63, "Hanging Torso Brain Out", ThingCategory.DECORATION),
    (70, "Burning Barrel", ThingCategory.DECORATION),
    (73, "Hanging Victim Guts Removed", ThingCategory.DECORATION),
    (74, "Hanging Victim Guts and Brain Removed", ThingCategory.DECORATION),
    (75, "Hanging Torso Looking Down", ThingCategory.DECORATION),
    (76, "Hanging Torso Open Skull", ThingCategory.DECORATION),
    (77, "Hanging Torso Looking Up", ThingCategory.DECORATION),
    (78, "Hanging Torso Brain Removed", ThingCategory.DECORATION),
    (79, "Pool of Blood", ThingCategory.DECORATION),
    (80, "Pool of Blood (small)", ThingCategory.DECORATION),
    (81, "Pool of Brains", ThingCategory.DECORATION),
    (85, "Tall Techno Floor Lamp", ThingCategory.DECORATION),
    (86, "Short Techno Floor Lamp", ThingCategory.DECORATION),
    (2028, "Floor Lamp", ThingCategory.DECORATION),
    (87, "Spawn Spot", ThingCategory.DECORATION),
    (89, "Spawn Shooter", ThingCategory.DECORATION),
    (2035, "Exploding Barrel", ThingCategory.DECORATION),
]

THING_TYPES: dict[int, tuple[str, ThingCategory]] = {row[0]: (row[1], row[2]) for row in _TABLE}

INVISIBLE_TYPES: frozenset[int] = frozenset({0, 11, 14, 87, 89})

SPRITE_PREFIXES: dict[int, str] = {
    1: "PLAY",
    2: "PLAY",
    3: "PLAY",
    4: "PLAY",
    3004: "POSS",
    9: "SPOS",
    65: "CPOS",
    3001: "TROO",
    3002: "SARG",
    58: "SARG",
    3003: "BOSS",
    3005: "HEAD",
    3006: "SKUL",
    7: "SPID",
    16: "CYBR",
    64: "VILE",
    66: "SKEL",
    67: "FATT",
    68: "BSPI",
    69: "BOS2",
    71: "PAIN",
    72: "KEEN",
    84: "SSWV",
    88: "BBRN",
    888: "DOGS",
    5: "BKEY",
    6: "YKEY",
    13: "RKEY",
    38: "RSKU",
    39: "YSKU",
    40: "BSKU",
    82: "SGN2",
    2001: "SHOT",
    2002: "MGUN",
    2003: "LAUN",
    2004: "PLAS",
    2005: "CSAW",
    2006: "BFUG",
    2007: "CLIP",
    2008: "SHEL",
    2010: "ROCK",
    17: "CELL",
    8: "BPAK",
    2046: "BROK",
    2047: "CELP",
    2048: "AMMO",
    2049: "SBOX",
    2011: "STIM",
    2012: "MEDI",
    2013: "SOUL",
    2014: "BON1",
    2015: "BON2",
    2018: "ARM1",
    2019: "ARM2",
    83: "MEGA",
    2022: "PINV",
    2023: "PSTR",
    2024: "PINS",
    2025: "SUIT",
    2026: "PMAP",
    2045: "PVIS",
    10: "PLAY",
    12: "PLAY",
    15: "PLAY",
    18: "POSS",
    19: "SPOS",
    20: "TROO",
    21: "SARG",
    22: "HEAD",
    23: "SKUL",
    25: "POL1",
    26: "POL6",
    27: "POL4",
    28: "POL3",
    29: "POL5",
    41: "CEYE",
    42: "FSKU",
    49: "GOR1",
    50: "GOR2",
    51: "GOR3",
    52: "GOR4",
    53: "GOR5",
    59: "GOR1",
    60: "GOR3",
    61: "GOR5",
    62: "GOR2",
    63: "GOR4",
    70: "FCAN",
    73: "HDB1",
    74: "HDB2",
    75: "HDB3",
    76: "HDB4",
    77: "HDB5",
    78: "HDB6",
    24: "POL5",
    79: "POB1",
    80: "POB2",
    81: "BRS1",
    2035: "BAR1",
    34: "CAND",
    35: "CBRA",
    48: "ELEC",
    30: "COL1",
    31: "COL2",
    32: "COL3",
    33: "COL4",
    36: "COL5",
    37: "COL6",
    43: "TRE1",
    54: "TRE2",
    44: "TBLU",
    45: "TGRN",
    46: "TRED",
    55: "SMBT",
    56: "SMGT",
    57: "SMRT",
    47: "SMIT",
    85: "TLMP",
    86: "TLP2",
    2028: "COLU",
}

_SPRITE_SUFFIX_OVERRIDES: dict[int, tuple[str, ...]] = {
    10: ("N0",),
    12: ("N0",),
    15: ("N0",),
    18: ("N0",),
    19: ("N0",),
    20: ("N0",),
    21: ("N0",),
    22: ("N0",),
    23: ("N0",),
}

MODULE = GameModule(
    thing_types=THING_TYPES,
    invisible_types=INVISIBLE_TYPES,
    sprite_prefixes=SPRITE_PREFIXES,
    sprite_suffix_overrides=_SPRITE_SUFFIX_OVERRIDES,
)
