"""Hexen thing type catalog — names and rendering categories.

Type IDs are INCOMPATIBLE with Doom and Heretic: e.g. type 5 = Winged statue
(Hexen) but type 5 = Fire Gargoyle (Heretic) / Blue Keycard (Doom).
Never mix with doom_types or heretic_types tables.

# TODO: support DECORATE/ZScript lumps so GZDoom PWADs can define new types.
"""

from .doom_types import ThingCategory

_TABLE: list[tuple[int, str, ThingCategory]] = [
    # ---- Player spawns --------------------------------------------------------
    (1, "Fighter Start", ThingCategory.PLAYER),
    (2, "Cleric Start", ThingCategory.PLAYER),
    (3, "Mage Start", ThingCategory.PLAYER),
    (4, "Player 4 Start", ThingCategory.PLAYER),
    (9100, "Player 5 Start", ThingCategory.PLAYER),
    (9101, "Player 6 Start", ThingCategory.PLAYER),
    (9102, "Player 7 Start", ThingCategory.PLAYER),
    (9103, "Player 8 Start", ThingCategory.PLAYER),
    # ---- Monsters -------------------------------------------------------------
    (31, "Green Chaos Serpent", ThingCategory.MONSTER),
    (34, "Reiver", ThingCategory.MONSTER),
    (107, "Centaur", ThingCategory.MONSTER),
    (114, "Dark Bishop", ThingCategory.MONSTER),
    (115, "Slaughtaur", ThingCategory.MONSTER),
    (120, "Stalker Boss", ThingCategory.MONSTER),
    (121, "Stalker", ThingCategory.MONSTER),
    (254, "Death Wyvern", ThingCategory.MONSTER),
    (8020, "Wendigo", ThingCategory.MONSTER),
    (8080, "Brown Chaos Serpent", ThingCategory.MONSTER),
    (10011, "Reiver (buried)", ThingCategory.MONSTER),
    (10030, "Ettin", ThingCategory.MONSTER),
    (10060, "Afrit", ThingCategory.MONSTER),
    (10080, "Heresiarch", ThingCategory.MONSTER),
    (10100, "Zedek", ThingCategory.MONSTER),
    (10101, "Traductus", ThingCategory.MONSTER),
    (10102, "Menelkir", ThingCategory.MONSTER),
    (10200, "Korax", ThingCategory.MONSTER),
    # ---- Weapons --------------------------------------------------------------
    (10, "Serpent Staff", ThingCategory.WEAPON),
    (12, "Quietus (blade)", ThingCategory.WEAPON),
    (13, "Quietus (cross)", ThingCategory.WEAPON),
    (16, "Quietus (hilt)", ThingCategory.WEAPON),
    (18, "Wraithverge (arc)", ThingCategory.WEAPON),
    (19, "Wraithverge (cross)", ThingCategory.WEAPON),
    (20, "Wraithverge (shaft)", ThingCategory.WEAPON),
    (21, "Bloodscourge (skull)", ThingCategory.WEAPON),
    (22, "Bloodscourge (stub)", ThingCategory.WEAPON),
    (23, "Bloodscourge (stick)", ThingCategory.WEAPON),
    (53, "Frost Shards", ThingCategory.WEAPON),
    (123, "Hammer of Retribution", ThingCategory.WEAPON),
    (8009, "Firestorm", ThingCategory.WEAPON),
    (8010, "Timon's Axe", ThingCategory.WEAPON),
    (8040, "Arc of Death", ThingCategory.WEAPON),
    # ---- Ammunition / Mana ----------------------------------------------------
    (122, "Blue Mana", ThingCategory.AMMO),
    (124, "Green Mana", ThingCategory.AMMO),
    (8004, "Combined Mana", ThingCategory.AMMO),
    # ---- Health ---------------------------------------------------------------
    (81, "Crystal Vial", ThingCategory.HEALTH),
    (82, "Quartz Flask", ThingCategory.HEALTH),
    # ---- Armor ----------------------------------------------------------------
    (8005, "Mesh Armor", ThingCategory.ARMOR),
    (8006, "Falcon Shield", ThingCategory.ARMOR),
    (8007, "Platinum Helm", ThingCategory.ARMOR),
    (8008, "Amulet of Warding", ThingCategory.ARMOR),
    # ---- Keys & puzzle items --------------------------------------------------
    (8030, "Steel Key", ThingCategory.KEY),
    (8031, "Cave Key", ThingCategory.KEY),
    (8032, "Axe Key", ThingCategory.KEY),
    (8033, "Fire Key", ThingCategory.KEY),
    (8034, "Emerald Key", ThingCategory.KEY),
    (8035, "Dungeon Key", ThingCategory.KEY),
    (8036, "Silver Key", ThingCategory.KEY),
    (8037, "Rusted Key", ThingCategory.KEY),
    (8038, "Horn Key", ThingCategory.KEY),
    (8039, "Swamp Key", ThingCategory.KEY),
    (8200, "Castle Key", ThingCategory.KEY),
    (9002, "Yorick's Skull", ThingCategory.KEY),
    (9003, "Heart of D'Sparil", ThingCategory.KEY),
    (9004, "Ruby Planet", ThingCategory.KEY),
    (9005, "Emerald Planet 1", ThingCategory.KEY),
    (9006, "Sapphire Planet 1", ThingCategory.KEY),
    (9007, "Daemon Codex", ThingCategory.KEY),
    (9008, "Liber Oscura", ThingCategory.KEY),
    (9009, "Emerald Planet 2", ThingCategory.KEY),
    (9010, "Sapphire Planet 2", ThingCategory.KEY),
    (9014, "Flame Mask", ThingCategory.KEY),
    (9015, "Glaive Seal", ThingCategory.KEY),
    (9016, "Holy Relic", ThingCategory.KEY),
    (9017, "Sigil of the Magus", ThingCategory.KEY),
    (9018, "Clock Gear (steel)", ThingCategory.KEY),
    (9019, "Clock Gear (bronze)", ThingCategory.KEY),
    (9020, "Clock Gear (steel in bronze)", ThingCategory.KEY),
    (9021, "Clock Gear (bronze in steel)", ThingCategory.KEY),
    # ---- Powerups -------------------------------------------------------------
    (30, "Porkalator", ThingCategory.POWERUP),
    (32, "Mystic Urn", ThingCategory.POWERUP),
    (33, "Torch", ThingCategory.POWERUP),
    (36, "Banishment Device", ThingCategory.POWERUP),
    (83, "Wings of Wrath", ThingCategory.POWERUP),
    (84, "Icon of the Defender", ThingCategory.POWERUP),
    (86, "Dark Servant", ThingCategory.POWERUP),
    (8000, "Fléchette", ThingCategory.POWERUP),
    (8002, "Boots of Speed", ThingCategory.POWERUP),
    (8003, "Krater of Might", ThingCategory.POWERUP),
    (8041, "Dragonskin Bracers", ThingCategory.POWERUP),
    (10040, "Banishment Device", ThingCategory.POWERUP),
    (10110, "Disc of Repulsion", ThingCategory.POWERUP),
    (10120, "Mystic Ambit Incant", ThingCategory.POWERUP),
    # ---- Decorations ----------------------------------------------------------
    (5, "Winged Statue", ThingCategory.DECORATION),
    (6, "Mossy Rock (tiny)", ThingCategory.DECORATION),
    (7, "Mossy Rock (small)", ThingCategory.DECORATION),
    (9, "Mossy Rock (medium)", ThingCategory.DECORATION),
    (15, "Mossy Rock (large)", ThingCategory.DECORATION),
    (17, "Chandelier (lit)", ThingCategory.DECORATION),
    (24, "Dead Tree", ThingCategory.DECORATION),
    (25, "Leafless Tree", ThingCategory.DECORATION),
    (26, "Mossy Tree 1", ThingCategory.DECORATION),
    (27, "Mossy Tree 2", ThingCategory.DECORATION),
    (28, "Tree Stump (burned)", ThingCategory.DECORATION),
    (29, "Tree Stump (bare)", ThingCategory.DECORATION),
    (37, "Tree Stump 1", ThingCategory.DECORATION),
    (38, "Tree Stump 2", ThingCategory.DECORATION),
    (39, "Large Mushroom 1", ThingCategory.DECORATION),
    (40, "Large Mushroom 2", ThingCategory.DECORATION),
    (41, "Medium Mushroom", ThingCategory.DECORATION),
    (42, "Small Mushroom 1", ThingCategory.DECORATION),
    (44, "Small Mushroom 2", ThingCategory.DECORATION),
    (45, "Small Mushroom 3", ThingCategory.DECORATION),
    (46, "Small Mushroom 4", ThingCategory.DECORATION),
    (47, "Small Mushroom 5", ThingCategory.DECORATION),
    (48, "Stalagmite Pillar", ThingCategory.DECORATION),
    (49, "Stalagmite (large)", ThingCategory.DECORATION),
    (50, "Stalagmite (medium)", ThingCategory.DECORATION),
    (51, "Stalagmite (small)", ThingCategory.DECORATION),
    (52, "Stalactite (large)", ThingCategory.DECORATION),
    (54, "Wall Torch (lit)", ThingCategory.DECORATION),
    (55, "Wall Torch (unlit)", ThingCategory.DECORATION),
    (56, "Stalactite (medium)", ThingCategory.DECORATION),
    (57, "Stalactite (small)", ThingCategory.DECORATION),
    (58, "Hanging Moss 1", ThingCategory.DECORATION),
    (59, "Hanging Moss 2", ThingCategory.DECORATION),
    (60, "Mossy Dead Tree", ThingCategory.DECORATION),
    (61, "Impaled Corpse", ThingCategory.DECORATION),
    (62, "Sleeping Corpse", ThingCategory.DECORATION),
    (63, "Tombstone (RIP)", ThingCategory.DECORATION),
    (64, "Tombstone (Shane)", ThingCategory.DECORATION),
    (65, "Tombstone (slimy)", ThingCategory.DECORATION),
    (66, "Tombstone (large cross)", ThingCategory.DECORATION),
    (67, "Tombstone (cross circle)", ThingCategory.DECORATION),
    (68, "Tombstone (small cross)", ThingCategory.DECORATION),
    (69, "Tombstone (Brian P)", ThingCategory.DECORATION),
    (71, "Hanging Corpse", ThingCategory.DECORATION),
    (72, "Stone Gargoyle (tall)", ThingCategory.DECORATION),
    (73, "Ice Gargoyle (tall)", ThingCategory.DECORATION),
    (74, "Ice Gargoyle (short)", ThingCategory.DECORATION),
    (76, "Stone Gargoyle (short)", ThingCategory.DECORATION),
    (77, "Battle Rag Banner", ThingCategory.DECORATION),
    (78, "Tall Tree 1", ThingCategory.DECORATION),
    (79, "Tall Tree 2", ThingCategory.DECORATION),
    (80, "Gnarled Tree 1", ThingCategory.DECORATION),
    (84, "Amulet of Warding (item)", ThingCategory.POWERUP),  # duplicate from armor
    (87, "Gnarled Tree 2", ThingCategory.DECORATION),
    (88, "Tree Log", ThingCategory.DECORATION),
    (89, "Icicle (large)", ThingCategory.DECORATION),
    (90, "Icicle (medium)", ThingCategory.DECORATION),
    (91, "Icicle (small)", ThingCategory.DECORATION),
    (92, "Icicle (tiny)", ThingCategory.DECORATION),
    (93, "Ice Spike (large)", ThingCategory.DECORATION),
    (94, "Ice Spike (medium)", ThingCategory.DECORATION),
    (95, "Ice Spike (small)", ThingCategory.DECORATION),
    (96, "Ice Spike (tiny)", ThingCategory.DECORATION),
    (97, "Brown Rock (large)", ThingCategory.DECORATION),
    (98, "Brown Rock (small)", ThingCategory.DECORATION),
    (99, "Black Rock", ThingCategory.DECORATION),
    (100, "Brick Rubble (large)", ThingCategory.DECORATION),
    (101, "Brick Rubble (small)", ThingCategory.DECORATION),
    (102, "Brick Rubble (medium)", ThingCategory.DECORATION),
    (103, "Pillar with Vase", ThingCategory.DECORATION),
    (104, "Pot (tall)", ThingCategory.DECORATION),
    (105, "Pot (medium)", ThingCategory.DECORATION),
    (106, "Pot (short)", ThingCategory.DECORATION),
    (108, "Lynched Corpse", ThingCategory.DECORATION),
    (109, "Lynched Corpse (heartless)", ThingCategory.DECORATION),
    (110, "Sitting Corpse", ThingCategory.DECORATION),
    (111, "Pool of Blood", ThingCategory.DECORATION),
    (116, "Twined Torch (lit)", ThingCategory.DECORATION),
    (117, "Twined Torch (unlit)", ThingCategory.DECORATION),
    (118, "Glitter Bridge", ThingCategory.DECORATION),
    (119, "3 Candles (lit)", ThingCategory.DECORATION),
    (140, "Teleport Smoke", ThingCategory.DECORATION),
    (8042, "Minotaur Statue (lit)", ThingCategory.DECORATION),
    (8043, "Minotaur Statue (unlit)", ThingCategory.DECORATION),
    (8044, "Rusty Gargoyle (tall)", ThingCategory.DECORATION),
    (8045, "Dark Lava Gargoyle (tall)", ThingCategory.DECORATION),
    (8046, "Light Lava Gargoyle (tall)", ThingCategory.DECORATION),
    (8047, "Bronze Gargoyle (tall)", ThingCategory.DECORATION),
    (8048, "Steel Gargoyle (tall)", ThingCategory.DECORATION),
    (8049, "Dark Lava Gargoyle (short)", ThingCategory.DECORATION),
    (8050, "Light Lava Gargoyle (short)", ThingCategory.DECORATION),
    (8051, "Bronze Gargoyle (short)", ThingCategory.DECORATION),
    (8052, "Steel Gargoyle (short)", ThingCategory.DECORATION),
    (8060, "Skull with Flame", ThingCategory.DECORATION),
    (8061, "Brazier with Flame", ThingCategory.DECORATION),
    (8062, "Destructible Tree", ThingCategory.DECORATION),
    (8063, "Chandelier (unlit)", ThingCategory.DECORATION),
    (8064, "Suit of Armor", ThingCategory.DECORATION),
    (8065, "Bell", ThingCategory.DECORATION),
    (8066, "Blue Candle (lit)", ThingCategory.DECORATION),
    (8067, "Iron Maiden", ThingCategory.DECORATION),
    (8068, "Evergreen Tree", ThingCategory.DECORATION),
    (8069, "Cauldron (lit)", ThingCategory.DECORATION),
    (8070, "Cauldron (unlit)", ThingCategory.DECORATION),
    (8071, "Chain (short)", ThingCategory.DECORATION),
    (8072, "Chain (long)", ThingCategory.DECORATION),
    (8073, "Hook with Heart", ThingCategory.DECORATION),
    (8074, "Chain with Large Hook", ThingCategory.DECORATION),
    (8075, "Chain with Small Hook", ThingCategory.DECORATION),
    (8076, "Chain with Spike Ball", ThingCategory.DECORATION),
    (8077, "Hook with Skull", ThingCategory.DECORATION),
    (8100, "Barrel", ThingCategory.DECORATION),
    (8101, "Shrub (small)", ThingCategory.DECORATION),
    (8102, "Shrub (large)", ThingCategory.DECORATION),
    (8103, "Hanging Bucket", ThingCategory.DECORATION),
    (8104, "Poisonous Mushroom", ThingCategory.DECORATION),
    (8500, "Wooden Beer Stein", ThingCategory.DECORATION),
    (8501, "Metal Beer Stein", ThingCategory.DECORATION),
    (8502, "Candle with Web (unlit)", ThingCategory.DECORATION),
    (8505, "Goblet (spilled)", ThingCategory.DECORATION),
    (8506, "Goblet (tall)", ThingCategory.DECORATION),
    (8507, "Goblet (short)", ThingCategory.DECORATION),
    (8508, "Goblet (silver)", ThingCategory.DECORATION),
    (8509, "Meat Cleaver", ThingCategory.DECORATION),
    (9011, "Yorick's Statue", ThingCategory.DECORATION),
    (9012, "Pedestal of D'Sparil", ThingCategory.DECORATION),
    (10090, "Spike Down", ThingCategory.DECORATION),
    (10501, "Small Flame", ThingCategory.DECORATION),
    (10503, "Large Flame", ThingCategory.DECORATION),
    # ---- Invisible markers (no in-game visual) --------------------------------
    (11, "Deathmatch Start", ThingCategory.DECORATION),
    (14, "Teleport Landing", ThingCategory.DECORATION),
    (113, "Leaf Spawner", ThingCategory.DECORATION),
    (1400, "Ambient: Stone", ThingCategory.DECORATION),
    (1401, "Ambient: Heavy", ThingCategory.DECORATION),
    (1402, "Ambient: Metal", ThingCategory.DECORATION),
    (1403, "Ambient: Creak", ThingCategory.DECORATION),
    (1404, "Ambient: Silence", ThingCategory.DECORATION),
    (1405, "Ambient: Lava", ThingCategory.DECORATION),
    (1406, "Ambient: Water", ThingCategory.DECORATION),
    (1407, "Ambient: Ice", ThingCategory.DECORATION),
    (1408, "Ambient: Earth", ThingCategory.DECORATION),
    (1409, "Ambient: Metal2", ThingCategory.DECORATION),
    (1410, "Ambient: Wind", ThingCategory.DECORATION),
    (3000, "Polyobject Anchor", ThingCategory.DECORATION),
    (3001, "Polyobject Start Spot", ThingCategory.DECORATION),
    (3002, "Polyobject Start Spot (crush)", ThingCategory.DECORATION),
    (9001, "Map Spot", ThingCategory.DECORATION),
    (9013, "Map Spot (gravity)", ThingCategory.DECORATION),
    (10000, "Fog Spawner", ThingCategory.DECORATION),
    (10225, "Bat Spawner", ThingCategory.DECORATION),
]

THING_TYPES: dict[int, tuple[str, ThingCategory]] = {row[0]: (row[1], row[2]) for row in _TABLE}

INVISIBLE_TYPES: frozenset[int] = frozenset({
    11,   # Deathmatch Start
    14,   # Teleport Landing
    113,  # Leaf spawner
    1400, 1401, 1402, 1403, 1404,  # Ambient sounds
    1405, 1406, 1407, 1408, 1409, 1410,
    3000, 3001, 3002,   # Polyobject markers
    9001, 9013,         # Map spots
    10000,              # Fog spawner
    10225,              # Bat spawner
})

_SPRITE_PREFIXES: dict[int, str] = {
    # Player spawns
    1: "PLAY", 2: "PLAY", 3: "PLAY", 4: "PLAY",
    9100: "PLAY", 9101: "PLAY", 9102: "PLAY", 9103: "PLAY",
    # Monsters
    31: "DEMN",   # Green Chaos Serpent
    34: "WRTH",   # Reiver
    107: "CENT",  # Centaur
    114: "BISH",  # Dark Bishop
    115: "CENT",  # Slaughtaur
    120: "SSPT",  # Stalker Boss
    121: "SSPT",  # Stalker
    254: "DRAG",  # Death Wyvern
    8020: "ICEY", # Wendigo
    8080: "DEM2", # Brown Chaos Serpent
    10011: "WRTH",# Reiver (buried)
    10030: "ETTN",# Ettin
    10060: "FDMN",# Afrit
    10080: "SORC",# Heresiarch
    10100: "PLAY",# Zedek
    10101: "CLER",# Traductus
    10102: "MAGE",# Menelkir
    10200: "KORX",# Korax
    # Weapons
    10: "WCSS",
    12: "WFR1",
    13: "WFR2",
    16: "WFR3",
    18: "WCH1",
    19: "WCH2",
    20: "WCH3",
    21: "WMS1",
    22: "WMS2",
    23: "WMS3",
    53: "WMCS",
    123: "WFHM",
    8009: "WCFM",
    8010: "WFAX",
    8040: "WMLG",
    # Ammo
    122: "MAN1",
    124: "MAN2",
    8004: "MAN3",
    # Health
    81: "PTN1",
    82: "PTN2",
    # Armor
    8005: "ARM1",
    8006: "ARM2",
    8007: "ARM3",
    8008: "ARM4",
    # Keys
    8030: "KEY1",
    8031: "KEY2",
    8032: "KEY3",
    8033: "KEY4",
    8034: "KEY5",
    8035: "KEY6",
    8036: "KEY7",
    8037: "KEY8",
    8038: "KEY9",
    8039: "KEYA",
    8200: "KEYB",
    9002: "ASKU",
    9003: "ABGM",
    9004: "AGMR",
    9005: "AGMG",
    9006: "AGMB",
    9007: "ABK1",
    9008: "ABK2",
    9009: "AGG2",
    9010: "AGB2",
    9014: "ASK2",
    9015: "AFWP",
    9016: "ACWP",
    9017: "AMWP",
    9018: "AGER",
    9019: "AGR2",
    9020: "AGR3",
    9021: "AGR4",
    # Powerups
    30: "PORK",
    32: "SPHL",
    33: "TRCH",
    36: "ATLP",
    83: "SOAR",
    84: "INVU",
    86: "SUMN",
    8000: "PSBG",
    8002: "SPED",
    8003: "BMAN",
    8041: "BRAC",
    10040: "TELO",
    10110: "BLST",
    10120: "HRAD",
    # Decorations
    5: "STTW",
    6: "RCK1",
    7: "RCK2",
    9: "RCK3",
    15: "RCK4",
    17: "CDLR",
    24: "TRE1",
    25: "TRE1",
    26: "TRE2",
    27: "TRE3",
    28: "STM1",
    29: "STM2",
    37: "STM3",
    38: "STM4",
    39: "MSH1",
    40: "MSH2",
    41: "MSH3",
    42: "MSH4",
    44: "MSH5",
    45: "MSH6",
    46: "MSH7",
    47: "MSH8",
    48: "SGMP",
    49: "SGM1",
    50: "SGM2",
    51: "SGM3",
    52: "SLC1",
    54: "WLTR",
    55: "WLTR",
    56: "SLC2",
    57: "SLC3",
    58: "MSS1",
    59: "MSS2",
    60: "SWMV",
    61: "CPS1",
    62: "CPS2",
    63: "TMS1",
    64: "TMS2",
    65: "TMS3",
    66: "TMS4",
    67: "TMS5",
    68: "TMS6",
    69: "TMS7",
    71: "CPS3",
    72: "STT2",
    73: "STT3",
    74: "STT4",
    76: "STT5",
    77: "BNR1",
    78: "TRE4",
    79: "TRE5",
    80: "TRE6",
    87: "TRE7",
    88: "LOGG",
    89: "ICT1",
    90: "ICT2",
    91: "ICT3",
    92: "ICT4",
    93: "ICM1",
    94: "ICM2",
    95: "ICM3",
    96: "ICM4",
    97: "RKBL",
    98: "RKBS",
    99: "RKBK",
    100: "RBL1",
    101: "RBL2",
    102: "RBL3",
    103: "VASE",
    104: "POT1",
    105: "POT2",
    106: "POT3",
    108: "CPS4",
    109: "CPS5",
    110: "CPS6",
    111: "BDPL",
    116: "TWTR",
    117: "TWTR",
    118: "TLGL",
    119: "CNDL",
    140: "TSMK",
    8042: "FBUL",
    8043: "FBUL",
    8044: "GAR1",
    8045: "GAR2",
    8046: "GAR3",
    8047: "GAR4",
    8048: "GAR5",
    8049: "GAR6",
    8050: "GAR7",
    8051: "GAR8",
    8052: "GAR9",
    8060: "FSKL",
    8061: "BRTR",
    8062: "TRDT",
    8063: "CDLR",
    8064: "SUIT",
    8065: "BBLL",
    8066: "CAND",
    8067: "IRON",
    8068: "XMAS",
    8069: "CDRN",
    8070: "CDRN",
    8071: "CHNS",
    8072: "CHNS",
    8073: "CHNS",
    8074: "CHNS",
    8075: "CHNS",
    8076: "CHNS",
    8077: "CHNS",
    8100: "BARL",
    8101: "SHB1",
    8102: "SHB2",
    8103: "BCKT",
    8104: "SHRM",
    8500: "TST1",
    8501: "TST2",
    8502: "TST3",
    8505: "TST6",
    8506: "TST7",
    8507: "TST8",
    8508: "TST9",
    8509: "TST0",
    9011: "STWN",
    9012: "GMPD",
    10090: "TSPK",
    10501: "FFSM",
    10503: "FFLG",
}

_DEFAULT_SPRITE_SUFFIXES: tuple[str, ...] = ("A0", "A1")


def get_sprite_suffixes(type_id: int) -> tuple[str, ...]:
    return _DEFAULT_SPRITE_SUFFIXES


def get_name(type_id: int) -> str:
    entry = THING_TYPES.get(type_id)
    return entry[0] if entry else f"Unknown (#{type_id})"


def get_category(type_id: int) -> ThingCategory:
    entry = THING_TYPES.get(type_id)
    return entry[1] if entry else ThingCategory.UNKNOWN


def get_sprite_prefix(type_id: int) -> str | None:
    return _SPRITE_PREFIXES.get(type_id)
