"""GL nodes reader — hardware rendering BSP data.

GL nodes are additional BSP data generated by glBSP or ZDBSP for
OpenGL-based source ports.  They supplement (not replace) the regular
BSP data with information optimized for polygon rendering.

Lump types:
- GL_VERT:  Extra vertices with fixed-point coordinates
- GL_SEGS:  GL segs referencing GL vertices
- GL_SSECT: GL subsectors built from GL segs
- GL_NODES: GL BSP nodes (same format as regular nodes)

The lumps appear after the map marker with a GL_ prefix matching the
map name: GL_MAP01, GL_E1M1, etc.

References:
- https://doomwiki.org/wiki/GL_nodes
- glBSP specification

Usage::

    from wadlib.lumps.glnodes import parse_gl_verts, parse_gl_segs

    gl_verts = parse_gl_verts(raw_bytes)
    gl_segs = parse_gl_segs(raw_bytes)
"""

from __future__ import annotations

import struct
from dataclasses import dataclass


@dataclass
class GlVertex:
    """A GL vertex with fixed-point coordinates (16.16 format)."""

    x: float
    y: float


@dataclass
class GlSeg:
    """A GL seg — references GL vertices and partner seg."""

    start_vertex: int
    end_vertex: int
    linedef: int  # 0xFFFF = miniseg (no linedef)
    side: int  # 0 = right, 1 = left
    partner_seg: int  # 0xFFFF = no partner

    @property
    def is_miniseg(self) -> bool:
        return self.linedef == 0xFFFF


@dataclass
class GlSubSector:
    """A GL subsector — count + first seg index."""

    seg_count: int
    first_seg: int


@dataclass
class GlNode:
    """A GL BSP node — same layout as vanilla nodes."""

    x: int
    y: int
    dx: int
    dy: int
    right_bbox: tuple[int, int, int, int]
    left_bbox: tuple[int, int, int, int]
    right_child: int
    left_child: int


# GL_VERT magic for v2+ format
_GL_VERT_MAGIC = b"gNd2"
_GL_VERT_V5_MAGIC = b"gNd5"


def parse_gl_verts(data: bytes) -> list[GlVertex]:
    """Parse a GL_VERT lump into a list of fixed-point vertices."""
    result: list[GlVertex] = []

    if data[:4] in (_GL_VERT_MAGIC, _GL_VERT_V5_MAGIC):
        # v2/v5: 4-byte magic + 32-bit fixed-point pairs
        pos = 4
        while pos + 8 <= len(data):
            fx, fy = struct.unpack("<ii", data[pos : pos + 8])
            result.append(GlVertex(fx / 65536.0, fy / 65536.0))
            pos += 8
    else:
        # v1: 16-bit integer pairs (same as regular VERTEXES)
        pos = 0
        while pos + 4 <= len(data):
            x, y = struct.unpack("<hh", data[pos : pos + 4])
            result.append(GlVertex(float(x), float(y)))
            pos += 4

    return result


def parse_gl_segs(data: bytes) -> list[GlSeg]:
    """Parse a GL_SEGS lump."""
    result: list[GlSeg] = []
    # Each seg: start(2) + end(2) + linedef(2) + side(2) + partner(2) = 10 bytes
    pos = 0
    while pos + 10 <= len(data):
        sv, ev, ld, side, partner = struct.unpack("<HHHHH", data[pos : pos + 10])
        result.append(GlSeg(sv, ev, ld, side, partner))
        pos += 10
    return result


def parse_gl_ssectors(data: bytes) -> list[GlSubSector]:
    """Parse a GL_SSECT lump."""
    result: list[GlSubSector] = []
    pos = 0
    while pos + 4 <= len(data):
        count, first = struct.unpack("<HH", data[pos : pos + 4])
        result.append(GlSubSector(count, first))
        pos += 4
    return result


def gl_verts_to_bytes(verts: list[GlVertex], version: int = 2) -> bytes:
    """Serialize GL vertices to a GL_VERT lump.

    *version* 1 uses 16-bit integers, 2 uses 32-bit fixed-point (recommended).
    """
    if version >= 2:
        result = bytearray(_GL_VERT_MAGIC)
        for v in verts:
            result += struct.pack("<ii", int(v.x * 65536), int(v.y * 65536))
        return bytes(result)
    result = bytearray()
    for v in verts:
        result += struct.pack("<hh", int(v.x), int(v.y))
    return bytes(result)


def gl_segs_to_bytes(segs: list[GlSeg]) -> bytes:
    """Serialize GL segs to a GL_SEGS lump."""
    result = bytearray()
    for s in segs:
        result += struct.pack(
            "<HHHHH", s.start_vertex, s.end_vertex, s.linedef, s.side, s.partner_seg
        )
    return bytes(result)


def gl_ssectors_to_bytes(ssectors: list[GlSubSector]) -> bytes:
    """Serialize GL subsectors to a GL_SSECT lump."""
    result = bytearray()
    for ss in ssectors:
        result += struct.pack("<HH", ss.seg_count, ss.first_seg)
    return bytes(result)


def gl_nodes_to_bytes(nodes: list[GlNode]) -> bytes:
    """Serialize GL nodes to a GL_NODES lump."""
    result = bytearray()
    for n in nodes:
        result += struct.pack(
            "<hhhhhhhhhhhhHH",
            n.x,
            n.y,
            n.dx,
            n.dy,
            *n.right_bbox,
            *n.left_bbox,
            n.right_child,
            n.left_child,
        )
    return bytes(result)


def parse_gl_nodes(data: bytes) -> list[GlNode]:
    """Parse a GL_NODES lump (same format as regular NODES)."""
    result: list[GlNode] = []
    pos = 0
    while pos + 28 <= len(data):
        values = struct.unpack("<hhhhhhhhhhhhHH", data[pos : pos + 28])
        result.append(
            GlNode(
                x=values[0],
                y=values[1],
                dx=values[2],
                dy=values[3],
                right_bbox=(values[4], values[5], values[6], values[7]),
                left_bbox=(values[8], values[9], values[10], values[11]),
                right_child=values[12],
                left_child=values[13],
            )
        )
        pos += 28
    return result
